export const THEME = {
    bgBase: '#f2f5f3',
    brandGreen: '#2E8B57',
    accentGold: '#FFD700',
    text: '#1a1a1a',
    black: '#121212',
    white: '#ffffff',
};

export const FONTS = {
    sans: '"Zen Kaku Gothic New", sans-serif',
    serif: '"Shippori Mincho", serif',
    mono: '"Courier New", Courier, monospace',
};

export const WORKS_DATA = [
    { 
        id: 1, 
        title: "ButterflyEffectCity/可不", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "活動者としての一歩目となる楽曲を作りました", 
        detailText: "ボカロPとしての一作目となる楽曲です。バタフライエフェクトというワードから連想し、一曲を仕上げました。",
        credits: ["Composition:三面相", "Illustration:らふぁえるsk"],
        color: "#FF6B6B" ,
        url: "https://youtu.be/TYKBm1GsSmA",
        image: "/images/butteerflyeffectCity.jpg",
    },
    { 
        id: 2, 
        title: "ナイト・アモーレ/星界", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "昭和歌謡な楽曲を制作しました", 
        detailText: "失恋した男に惚れている女性をテーマにした楽曲を作りました。星界楽曲コンテストへの参加曲として制作しました。昭和歌謡の雰囲気をゴリゴリに醸し出すという方向性で制作を進めました。",
        credits: ["Composition:三面相", "Illustration:櫛米"],
        color: "#FF6B6B" ,
        url: "https://youtu.be/yupa62YiQFg",
        image: "/images/nightamore.jpg",
    },
    { 
        id: 3, 
        title: "産声/可不・星界", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "民族的な要素を意識したデュエット曲を作りました", 
        detailText: "星界楽曲コンテストへの参加曲として制作しました。デュエットソングに挑戦してみようと思い、今までよりアコースティックな仕上がりを意識しました。",
        credits: ["Composition:三面相"],
        color: "#FF6B6B" ,
        url: "https://youtu.be/UOYN5jK454U",
        image: "/images/ubugoe.jpg",
    },
    { 
        id: 4, 
        title: "乱調ヒムノディ／星界", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "スランプ状態をテーマにした楽曲を作りました", 
        detailText: "スランプ状態に陥った時のメモをもとに制作した楽曲です。ボカコレに初参加しました。\n\nタイミング補正とピッチ補正で無理やりラップパートを作ったのは良い思い出です。",
        credits: ["Composition:三面相", "Movie:月華"],
        color: "#FF6B6B",
        url:"https://youtu.be/d4iwXL_yZNc",
        image: "/images/rantyou.jpg",
    },
    { 
        id: 5, 
        title: "電話線、三番ホーム/裏命", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "失恋をテーマにした楽曲を作りました", 
        detailText: "パンク的な楽曲。裏命楽曲コンテストに参加したときの曲です。\n\n頑張って地元を撮影していた痕跡があります。",
        credits: ["Composition:三面相", "VocalEdit:風祭瑛紀", "GuiterAssistant:花嶋"],
        color: "#FF6B6B",
        url:"https://youtu.be/-tQC2JsnOwc",
        image: "/images/denwasen3banhome.jpg",
    },
    { 
        id: 6, 
        title: "ボカロの資金がありません！！/初音ミク", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "「お金がない！」をテーマにした楽曲を作りました", 
        detailText: "お金がない！って曲です。当時のぼやきも入ってます。恥ずかしい。",
        credits: ["Composition:三面相", "Illustration:黒岩秀太!!"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm41743994",
        image: "/images/novocaloidmoney.jpg",
    },
    { 
        id: 7, 
        title: "バベル/ノア", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "軽やかに歌い上げるケルト楽曲を作りました", 
        detailText: "バベルという楽曲です。ボカデュオというものに参加してみました。\n\n初めてボーカルを入れてもらった思い出深い楽曲でもあります。",
        credits: ["Composition:三面相", "Illustration,Movie:櫛米","Vocal:Fusb"],
        color: "#FF6B6B",
        url:"https://youtu.be/KSlT4hv3QKw",
        image: "/images/babel.jpg",
    },
    { 
        id: 8, 
        title: "レボルシオン/狐子", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "真っすぐなロック楽曲を作りました", 
        detailText: "真っすぐなロック楽曲。狐子楽曲コンテストに参加したときの曲です。",
        credits: ["Composition:三面相"],
        color: "#FF6B6B",
        url:"https://youtu.be/Nu3TOOYh6-4",
        image: "/images/reborusion.jpg",
    },
    { 
        id: 9, 
        title: "【DTM鯖】ダンスロボットダンス", 
        type: "music", 
        year: "2023", 
        role: "Remix", 
        desc: "remix合作に参加しました", 
        detailText: "DTM鯖合作に参加しました。ダンスロボットダンスのリミックスです。",
        credits: ["Remixe:	Aa, cottown, lyqjw, mikage, nahi, Taguchi Hideo, だいす, レラー, 荒井　暁, 三面相, 澄石亜卵, 長谷川迷子, 夢見川るい, 鼬炉ヒソ", "Illustration: 桶猫, 残響室, 森永謹製, 米村ソウマ"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm42576695",
        image: "/images/dancerobotRemix.jpg",
    },
    { 
        id: 10, 
        title: "エンドロールの箱で/花奏かのんβ", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "一年の終わりをイメージした曲を作りました", 
        detailText: "年の瀬に楽曲を制作しました。渋谷系とハイパーフリップを自分なりに落とし込もうと考えた結果、情報量をカットアップによって埋め尽くすことを考えてました。",
        credits: ["Composition:三面相"],
        color: "#FF6B6B",
        url:"https://youtu.be/n_s7wbispd4",
        image: "/images/endrolebox.jpg",
    },
    { 
        id: 11, 
        title: "きっと : だれか ; ぼくら / 可不", 
        type: "music", 
        year: "2024", 
        role: "Composition", 
        desc: "旅立つ人へのエールを送る曲を作りました", 
        detailText: "独り立ちする自分をテーマに制作した楽曲です。渋谷系の音楽を自分なりに落とし込み、カットアップを多様したポップスを制作しました。\n\n撮影のロケーションは全て地元です。コマ撮りを力業で行いました。",
        credits: ["Composition:三面相", "Movie:三面相"],
        color: "#FF6B6B",
        url:"https://youtu.be/egZJaL9Lq3I",
        image: "/images/kittodarekabokura.jpg",
    },
    { 
        id: 12, 
        title: "ょく / 初音ミク【三択はむり】", 
        type: "music", 
        year: "2024", 
        role: "Arrangement", 
        desc: "楽曲に編曲で参加しました", 
        detailText: "ボカタッグというイベントにて三択はむりというチームを組みました。編曲を担当しました。\n\n荘厳な雰囲気から始まり、フューチャーベースのようなドロップに繋がる展開は、作っていてとても楽しかったです。",
        credits: ["Composition:稲むり", "Arrangement:三面相", "Illustration:uotak", "Movie:木葉はづく"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm43683720",
        image: "/images/yoku.jpg",
    },
    { 
        id: 13, 
        title: "【猫じゃらし道】それと同じ陽の暖かさ / ゲキヤクβ・カゼヒキβ", 
        type: "music", 
        year: "2024", 
        role: "Arrangement", 
        desc: "楽曲に編曲で参加しました", 
        detailText: "ボカタッグというイベントにて猫じゃらし道というチームを組みました。編曲を担当しました。\n\n「テクノポップにしてください」というオーダーを受け、楽曲のやさしさの部分とテクノポップを両立させられるように意識して制作しました。",
        credits: ["Composition:稲むり", "Arrangement:三面相", "Illustration:並木道", "Movie:稲むり"],
        color: "#FF6B6B",
        url:"https://youtu.be/15z0vwS77u0",
        image: "/images/soretoonaji.jpg",
    },
    { 
        id: 14, 
        title: "鏡像異性体", 
        type: "entame", 
        year: "2024", 
        role: "DJ", 
        desc: "鏡像異性体というイベントにDJで出演しました", 
        detailText: "合成音声系のDJイベントに出演しました。第一回のイベントで初めてのDJ出演という、貴重な機会を頂きました。",
        credits: ["DJ:三面相,芥田レンリ,Right,ざき,Uyamichi,Uyamichi", "VJ:扉,Zect", "Staff:アライグマ,観測者48", "Organizer:風祭瑛紀"],
        color: "#4ECDC4",
        url:"https://x.com/enantiomer_eve/status/1790714101284676068",
        image: "/images/kyoudouiseitaiVol1.jpg",
    },
    { 
        id: 15, 
        title: "V.A. - SUPER MURAKAMI BEST HITS", 
        type: "music", 
        year: "2024", 
        role: "Composition", 
        desc: "声ネタ縛りコンピレーションアルバムに参加しました", 
        detailText: "村上苺さんのボイスサンプルを用いた楽曲を作るというコンピレーションアルバムに楽曲を提供しました。声ネタはなんぼあってもいい。",
        credits: ["Composition:ijimi,trekk,ハヤトムラカミ,10-U,crash909☆ 啊痾誒都哇嗚哇咦,糸魚川 鼎,M9RVEN,Legend of 阪口,Eyhz & Violet Delta,dj patriot,Kaichirock,Ide_Co,LieDeeDonk,ドンツカチェィッフォー,WⱯꓥƎ,ゴローニャ雨宮,三面相","Special Thanks:村上苺","Illustration:HUKRiTAX","Design:Occupied Territories","Organizer:Lost Frog Productions"],
        color: "#FF6B6B",
        url:"https://lostfrog.bandcamp.com/album/super-murakami-best-hits",
        image: "/images/murakamibest.jpg",
    },
    { 
        id: 16, 
        title: "希望の糸 / 花隈千冬", 
        type: "music", 
        year: "2024", 
        role: "Composition", 
        desc: "「冷麦高校そうめん部」公式テーマソングを作りました", 
        detailText: "202X年夏アニメ「冷麦高校そうめん部」公式テーマソング『希望の糸』を制作しました。イントロ～Bメロまでの作詞、作曲、編曲を担当しました。ナレーション指導も少し行っています。\nサビからは夜丹れにやさんの担当です。\n\n〇あらすじ\n桜井ゆう(さくらいゆう)は冷麦高校の一年生。冷麦高校そうめん部に入部するものの、部室には冷麦しかなくて・・・・？冷麦高校そうめん部を巡るドタバタ青春そうめんストーリー！",
        credits: ["Composition:三面相,夜丹れにや", "Lyric:uotak,三面相,夜丹れにや", "Illustration:ももま", "Logo:ALNiCo", "Movie:さかもとさかし", "Shooting processing:Hatty.G", "Narration:三面相,空穂れい", "Planning and concept:uotak"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm44021435",
        image: "/images/soumenbu.jpg",
    },
    { 
        id: 17, 
        title: "#雑ボカ 〜雑にボカロをかけれる会〜 第19回",
        type: "entame", 
        year: "2024", 
        role: "DJ", 
        desc: "VRCイベント『雑ボカ』の第19回に出演しました", 
        detailText: "ボーカロイド楽曲の流れるVRCイベントに出演しました。慣れないVRCのサポートもしてもらい、助かりました。\n\nマッシュアップや新曲などを複数披露し、サプライズの多いアクトになりました。",
        credits: ["DJ:TMPら,三面相,d.j.ァネイロ,Molluscholar", "VJ:SELDO,木葉はづく,HB", "Flyer:艾 / moxa,SEDO Sounder", "Organizer:ゆーいぢ"],
        color: "#4ECDC4",
        url:"https://www.nicovideo.jp/watch/sm44153767",
        image: "/images/zatuboka.jpg",
    },
    { 
        id: 18, 
        title: "CDs＋いよわ『きゅうくらりん』即興リミックス",
        type: "entame", 
        year: "2024", 
        role: "Remix", 
        desc: "イベントにCDsとして出演しました", 
        detailText: "東京ゲームショウのガレリアブースにて、いよわさんの楽曲『きゅうくらりん』を即興リミックスするという企画に参加しました。\n緊張感のある中でのリミックスは刺激的で貴重な経験でした。",
        credits: ["Performers(Remix):原口沙輔,おし怪,フロクロ,三面相,長谷川迷子", "Performers(Movie):木葉はづく","Performers:いよわ"],
        color: "#4ECDC4",
        url:"https://x.com/GALLERIA_GM/status/1839878767990452463",
        image: "/images/gareriremixCds.jpg",
    },
    { 
        id: 19, 
        title: "DJ24",
        type: "entame", 
        year: "2024", 
        role: "DJ", 
        desc: "イベントにDJとして出演しました", 
        detailText: "年末に24時間ボカロDJを行うというイベントに出演しました。\nあまりに出演者が多いため、クレジットを省略させていただきます。",
        credits: ["DJ,VJ,ライブペイント:出演者が多いため省略"],
        color: "#4ECDC4",
        url:"https://x.com/DJVocaSpot/status/1840387427934024051",
        image: "/images/DJ24.jpg",
    },
    { 
        id: 20, 
        title: "咳",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "コンピレーションアルバム『咳』に参加しました", 
        detailText: "カゼヒキをテーマにしたコンピレーションアルバムに楽曲で参加しました。「今日＋これからの日記」という楽曲です。",
        credits: ["Composition:新日本開発機構,Mi7s3,オヨイダキビス,MIDy,三面相,Mealerrand,四度寝,おし怪,Wa!ter,あずきねこp,微円,異星鐘,橘しとら,二錠,是", "Mastering:SOZEN OTSUBO", "Artwork:稲むり", "Movie,Logo design:木葉はづく"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm44518881",
        image: "/images/seki.jpg",
    },
    { 
        id: 21, 
        title: "憧れbootleg/初音ミク",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "トランスポップ楽曲を制作しました", 
        detailText: "ハイパートランスを意識したボカロ楽曲を制作しました。憧れるという意識の奥に潜む罪悪感をイメージしています。",
        credits: ["Composition:三面相", "Movie:さかもとさかし"],
        color: "#FF6B6B",
        url:"https://youtu.be/lLUPKj_wgyM",
        image: "/images/akogareboot.png",
    },
    { 
        id: 22, 
        title: "【DTM鯖合作】おちゃめ機能",
        type: "music", 
        year: "2025", 
        role: "Remixe", 
        desc: "Remix合作に参加しました", 
        detailText: "DTM鯖Remix合作に参加しました。大人数で参加する合作はわちゃわちゃしてて楽しいです。",
        credits: ["Remixer:送電球,mucell,色元,島村卯月,lyqjw,ひるりゅー,ねも三ヶ原小造山武夫,mikage,三面相,とるかや,コットタウン,漣音,Fanu,微円,かにパ,トキノヤッマ,フロクロ,夜丹れにや,火ノｒ祈,夢見川るい", "Movie:コソアド,空穂れい,澄石亜卵,空島ばんし,ウサクラジュワコ,シキ式,ぬかくぎ,虚無沢まるり", "Mix,Mastering:夢見川るい"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm44562404",
        image: "/images/otyameRemix.jpg",
    },
    { 
        id: 23, 
        title: "Hello, Morning (rework by CDs)",
        type: "music", 
        year: "2025", 
        role: "Remixe", 
        desc: "Remixに参加しました", 
        detailText: "Hello, Morning (rework by CDs)にremixで参加しました。大事な節目の為のリミックス、心を込めて制作しました。",
        credits: ["Remixer:sober bear,Saku,higma,なみぐる,Namitape,すずめのめ,factal,三面相,マサラダ,長谷川迷子,MIDy,原口沙輔", "Movie:melonade,木葉はづく,HIRO,おし怪,Bivi,mintoll,マサラダ", "Animation:えいりな刃物", "Sound textuer:factal", "Jacket,Thumbnail:木葉はづく", "Mix,Mastering:原口沙輔"],
        color: "#FF6B6B",
        url:"https://youtu.be/Y_MLRgQZRig",
        image: "/images/HelloJacket.jpg",
    },
    { 
        id: 24, 
        title: "イガク♡着せ替えコレクション～キラって☆デコって☆メタメタREMIX～ / 三面相 vs d.j.ァネイロ",
        type: "music", 
        year: "2025", 
        role: "Remixe / Logo design", 
        desc: "Remix合作をしました", 
        detailText: "ァネイロとイガクのremix合作をしました。限りなくカオスに、ネタのオンパレードで、リミックスバトルです。",
        credits: ["Remixe:d.j.ァネイロ,三面相", "Logo:三面相", "Movie:LitMus"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm44677545",
        image: "/images/igakuremix.jpg",
    },
    { 
        id: 25, 
        title: "lite to.flac",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "コンピレーションアルバムに参加しました", 
        detailText: "重音テトをテーマにしたアルバム『lite to.flac』に楽曲で参加しました。\n『メモ_この環境で生きる為の10の方法（また今度考える）』という楽曲です。長ったらしい。",
        credits: ["Composition:Saku,原口沙輔,MIDy,すずめのめ,三面相,factal,ァネイロ,長谷川迷子,norimaro", "Jacket illust:握り拳"],
        color: "#FF6B6B",
        url:"https://booth.pm/ja/items/6986076",
        image: "/images/litetoflac.jpg",
    },
    { 
        id: 26, 
        title: "TRY FORCE v3.0",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "DJとして出演しました", 
        detailText: "TRY FORCE v3.0にDJとして出演しました。\n大阪の出演、是非お待ちしております。",
        credits: ["DJ:音無あふ,とうか,梔,https,fluspicious,M4ss0,shi_ra,つくにだ,猫咲さくら,緋築,るつ,Right,星花ゆめ,はくるり", "VJ:電池芋,Zect,Hakururi"],
        color: "#4ECDC4",
        url:"https://x.com/Try04_/status/1896162495460757727",
        image: "/images/try3.jpg",
    },
    { 
        id: 27, 
        title: "Soundtrap遊び",
        type: "fun", 
        year: "2025", 
        role: "Composition", 
        desc: "オンラインDTMで遊びました", 
        detailText: "オンラインでDTMのできるサービスで合作をしました。マルチDTM",
        credits: ["Composition:かかこ,kuma,三面相,厚寝巻"],
        color: "#FFD700",
        url:"https://x.com/kakothk/status/1902477682149093578",
        image: "/images/soundtrap.png",
    },
    { 
        id: 28, 
        title: "クリラジ〜明日から作曲家〜",
        type: "fun", 
        year: "2025", 
        role: "Radio personality / Logo design", 
        desc: "友人とラジオを始めました", 
        detailText: "大学の友人とラジオをやっています。絶賛配信中。\n音楽生活や日常のぼやきを話しています。",
        credits: ["Radio personality:森田康太郎(三面相),井上暖之"],
        color: "#FFD700",
        url:"https://creators.spotify.com/pod/profile/gbo3oabestg/episodes/0-e30b26n",
        image: "/images/kuriraji.png",
    },
    { 
        id: 29, 
        title: "おいかける",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "コンピレーションアルバムに参加しました", 
        detailText: "追跡をテーマにしたコンピレーションアルバム『おいかける』に参加しました。\n風祭瑛紀さんとの合作です。ニューロなドラムンベースです。",
        credits: ["Composition:風祭瑛紀×三面相,Gojikan,神無月ルミカ,不響和音,Stellar,Gyr0,風祭瑛紀,トキノヤッマ", "Jacket art:トキノヤッマ"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm44883627",
        image: "/images/おいかける.png",
    },
    { 
        id: 30, 
        title: "おはよう",
        type: "music", 
        year: "2025", 
        role: "Composition / design", 
        desc: "1stアルバムを制作しました", 
        detailText: "三面相の1stアルバム『おはよう』を制作しました。ジャケット等のデザインも行っています。\n各種サブスクサービスで聞くことも可能です。\n\n三面相としての名刺代わりになるようなアルバムとなっています。",
        credits: ["Composition,design:三面相", "STEM Mastering:Rei (studio JEN)"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm44904337",
        image: "/images/おはよう.png",
    },
    { 
        id: 31, 
        title: "splash rush",
        type: "music", 
        year: "2025", 
        role: "Composition / design", 
        desc: "bandcampに楽曲を配信しました", 
        detailText: "シングルをbandcampにて配信しました。サンプルチョップの風味が強い爽やかエレクトロポップです。",
        credits: ["Composition,Jacket design:三面相"],
        color: "#FF6B6B",
        url:"https://sanmenso.bandcamp.com/track/splash-rush",
        image: "/images/splashrush.png",
    },
    { 
        id: 32, 
        title: "Cut,solid,solar panel",
        type: "fun", 
        year: "2025", 
        role: "Composition / design", 
        desc: "CSSで遊びました", 
        detailText: "#CSS_Soundにて遊びました。極限まで切り貼りです。",
        credits: ["Composition,Jacket design:三面相"],
        color: "#FFD700",
        url:"https://soundcloud.com/lb3uw4iphdxy/css_cutsolidsolar-panel",
        image: "/images/CSSfun.png",
    },
    { 
        id: 33, 
        title: "Coffee Break Down / 花隈千冬",
        type: "music", 
        year: "2025", 
        role: "Composition / Movie", 
        desc: "チルエレクトロなMVを投稿しました", 
        detailText: "『おはよう』よりCoffee Break DownのMVを投稿しました。\nボサノバをエレクトロに変調、後半は倍速に加工させた楽曲を制作しました。\n\n映像はモーションリリックを減速で書き出し、撮影。そのデータを倍速に加工させて制作しています。",
        credits: ["Composition,Movie:三面相", "Filming assistant:蜘蛛海月", "STEM Mastering:Rei (studio JEN)"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm45058224",
        image: "/images/Coffeebreak.png",
    },
    { 
        id: 34, 
        title: "鏡像異性体vol.2",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにDJとして出演しました", 
        detailText: "『鏡像異性体vol.2』にDJとして出演しました。共演者の楽曲のRemixなども制作しました。",
        credits: ["DJ:三面相,appy,有部遼,ИASU,ざき,right,風祭瑛紀", "VJ:zact,Hakururi", "Organizer:風祭瑛紀"],
        color: "#4ECDC4",
        url:"https://x.com/enantiomer_eve/status/1911381350579339547",
        image: "/images/kyoudouiseitaivol2.jpg",
    },
    { 
        id: 35, 
        title: "DJs for anywere 001",
        type: "fun", 
        year: "2025", 
        role: "DJ", 
        desc: "サプライズ型イベントにDJとして参加しました", 
        detailText: "DJsに出没しました。OPアナウンスも行っています。",
        credits: ["DJ:大人数により省略"],
        color: "#FFD700",
        url:"https://x.com/CDs_inter/status/1936250376598307004",
        image: "/images/DJs1.jpg",
    },
    { 
        id: 36, 
        title: "LOLOLOLOVELOID vol.3",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにDJとして参加しました", 
        detailText: "VRC内のイベント『LOLOLOLOVELOID vol.』3にDJとして参加しました。",
        credits: ["DJ:d.j.ァネイロ,三面相,𝗡𝟰𝗚𝟭𝘁,んべべ商会,電池芋,", "VJ:らぎ汰,しろのん", "Staff:白鮭,おおつく", "Flyer illust:たれっさー", "Flyer design:白鮭"],
        color: "#4ECDC4",
        url:"https://x.com/Quartz_Tea/status/1937118483202162899",
        image: "/images/Lololo3.jpg",
    },
    { 
        id: 37, 
        title: "消えちゃう世界と僕、ソリチュード / 知声",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "ボカロ渋谷系楽曲を投稿しました", 
        detailText: "ボカロ渋谷系投稿祭り2025に『消えちゃう世界と僕、ソリチュード / 知声』という楽曲を投稿しました。",
        credits: ["Composition:三面相"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm45161376",
        image: "/images/きえちゃう.jpg",
    },
    { 
        id: 38, 
        title: "ロゴ制作",
        type: "entame", 
        year: "2025", 
        role: "Logo design", 
        desc: "三面相のロゴを制作しました", 
        detailText: "自分の制作に使うロゴをデザインしました。\nアイコンと三つの△、sとoから成り立つポップなロゴです。",
        credits: ["Logo design:三面相"],
        color: "#4ECDC4",
        image: "/images/SANMENlogoworks.jpg",
    },
    { 
        id: 39, 
        title: "あみだくじコンピ",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "コンピレーションアルバムに参加しました", 
        detailText: "コンピレーションアルバム『あみだくじコンピ』に楽曲で参加しました。\n曲の内容をあみだくじで決める前代未聞の内容に冷や汗だらだらで制作しました。",
        credits: ["Composition:三面相, Aa, 米教タルタル, 夜丹れにや, ETE, おおつく, .+, MIDy, Mealerrand, 安藤なれど, おし怪", "Mastering:駱駝法師", "Illustration:のぞみ"],
        color: "#FF6B6B",
        url:"https://x.com/Quartz_Tea/status/1945453379670720820",
        image: "/images/amidakuji.jpg",
    },
    { 
        id: 40, 
        title: "重ねトマト缶 (SANMENso Remix)",
        type: "music", 
        year: "2025", 
        role: "Remix", 
        desc: "Remixをしました（二次創作）", 
        detailText: "重ねトマト缶のリミックスをしました。",
        credits: ["Remixer:三面相"],
        color: "#FF6B6B",
        url:"https://soundcloud.com/sanmenso/sanmenso-remix",
        image: "/images/トマト　SAMUNE.jpg",
    },
    { 
        id: 41, 
        title: "GOLD DISC 25.08.16",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにCDs crewとして参加しました", 
        detailText: "GOLDDISCにCDs crewとして参加しました。",
        credits: ["Performer:CDs crew"],
        color: "#4ECDC4",
        url:"https://zerotokyo.zaiko.io/e/gold-disc-0816",
        image: "/images/GoldDiscCds.jpg",
    },
    { 
        id: 42, 
        title: "CDs YouTubeMusicWeekend 2025",
        type: "entame", 
        year: "2025", 
        role: "Composition / act", 
        desc: "『CDs 2025』に出演しました", 
        detailText: "『CDs 2025』にトラック制作と出演をしました。CDsに関係する音声のカットアップや音声提供、動画内で出演もしています。",
        credits: ["Performer:CDs"],
        color: "#4ECDC4",
        url:"https://youtu.be/ci4NOQnobyc",
        image: "/images/CDsYMW2025.jpg",
    },
    { 
        id: 43, 
        title: "ℬaⓢ9 - Chill",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにDJとして出演しました", 
        detailText: "VRCのイベント『ℬaⓢ9 - Chill』にDJとして出演しました。\nDJコントローラーのエコーやリバーブを使ったアンビエントなDJをしました。アルバムのインスト曲を織り交ぜる演出も行いました。",
        credits: ["DJ:おおつく,d.j.ァネイロ,三面相,namitape,POPFACES", "VJ:あたたかい水族館,.+"],
        color: "#4ECDC4",
        url:"https://x.com/Quartz_Tea/status/1963542562209218923",
        image: "/images/basschill.jpg",
    },
    { 
        id: 44, 
        title: "つながり v1.0",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにDJとして出演しました", 
        detailText: "イベント『つながり v1.0』にDJとして出演しました。\n僕を中心にした謎のコンテンツ【培養オム】を巻き込んだ「培養オムLive set」を行いました。",
        credits: ["DJ:三面相,稲むり,長谷川迷子,Steller,おおつく,空穂れい,ゆーいぢ,TMPら", "VJ:Philtz（オオウチアラタ, uotak）,melonade,培養オム,交互,のぞみ", "Organizer:TMPら"],
        color: "#4ECDC4",
        url:"https://youtu.be/SyGYHXMDgSw",
        image: "/images/Tunagari.jpg",
    },
    { 
        id: 45, 
        title: "FOR UNREAL TO REAL",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにDJとして出演しました", 
        detailText: "イベント『合成音声のうたげ東名阪ツアー「FOR UNREAL TO REAL」』の大阪公演にDJとして出演しました。\n片方ギタリスト、片方サウンドデザイナーという事でイントロクイズやギターカバーをするなどの演出を行いました。",
        credits: ["DJ:GESO,MIDy,simotaka B2B U/会長,r-906,sober bear,おおつく,三面相 B2B 四度寝 B2B おし怪,ニシ B2B たかっきー,駱駝法師", "VJ:Mano.hsmt,SELDO", "Organizer:駱駝法師"],
        color: "#4ECDC4",
        image: "/images/UtageOsaka.png",
    },
    { 
        id: 46, 
        title: "VIRAL 2025.10.19",
        type: "entame", 
        year: "2025", 
        role: "DJ", 
        desc: "イベントにDJとして出演しました", 
        detailText: "イベント『VIRAL』にDJとして出演しました。長谷川迷子さんとのB2Bです。",
        credits: ["DJ,VJ:出演者多数のため省略"],
        color: "#4ECDC4",
        image: "/images/VIRAL.jpg",
    },
    { 
        id: 47, 
        title: "培養オム　BGM・SE制作",
        type: "fun", 
        year: "2025", 
        role: "Composition", 
        desc: "BGMを制作しました", 
        detailText: "培養オムに上がっていた映像にBGMとSEをつけました。",
        credits: ["Composition:三面相, Movie:【匿名】"],
        color: "#FFD700",
        url:"https://x.com/biomu_/status/1979857862479552865",
        image: "/images/biomu.png",
    },
    { 
        id: 48, 
        title: "hard",
        type: "fun", 
        year: "2025", 
        role: "Act", 
        desc: "セッションをしました。", 
        detailText: "sessionをしました。テープエコー等で遊んでいます",
        credits: ["Act:三面相,零進法,d.j.ァネイロ"],
        color: "#FFD700",
        url:"https://www.youtube.com/live/fDZq0DSR3aY",
        image: "/images/CDssesionhard.jpg",
    }, 
    { 
        id: 49, 
        title: "終点帰行",
        type: "music", 
        year: "2025", 
        role: "Composition", 
        desc: "コンピレーションアルバムに参加しました", 
        detailText: "架空のフリーホラーゲームの分岐エンディングをテーマにした『終点帰行』に楽曲で参加しました。ブラクラ的楽曲に仕上げました。",
        credits: ["Composition:あなざ〜せかい,イントナル森,鬱桑型,オヨイダキビス,OLDUCT,コットタウン,三面相,しゃいと,Aa,ハサキトオル,パルチーノ,ほいっぷ,mikage,Mi7s3,mucell,モエソデ,ヤヅキ", "Jacket illustration:ひとさじ", "Illustration:ハサキトオル,コットタウン,ほいっぷ", "Mastering:かごめP"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm45629216",
        image: "/images/endkikou.jpg",
    },   
    { 
        id: 50, 
        title: "vitali ga nai",
        type: "music", 
        year: "2025", 
        role: "Composition / Movie", 
        desc: "寝れないけどやる気がない時をイメージした楽曲を投稿しました", 
        detailText: "どうしても寝れない日、でも何もやる気がない日をイメージして制作した楽曲です。歌詞はゆるくて曲調は渋いというギャップを意識して制作しました。\n\nMVでAfteEffectのエクスプレッションを利用し、一つのオーディオスペクトラムで複数のパートの音を表現できるように試してみました。",
        credits: ["Composition,Movie:三面相", "STEM Mastering:Rei (studio JEN)"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm45629216",
        image: "/images/vitaliganai.png",
    },
    { 
        id: 51, 
        title: "2025's VOCALIFE",
        type: "entame", 
        year: "2026", 
        role: "DJ", 
        desc: "イベントにDJmixで出演しました", 
        detailText: "2025年のボーカロイドを、インターネットの一つとして捉えたDJmixを作成し、イベントで流しました。会場を巻き込んだクイズ等も織り交ぜています。\n\nsupported by ゆーいぢで送りしました。\n\n映像協力：uotak, さかもとさかし, .+, 霚",
        credits: ["DJ＆performance:三面相,感状線,駱駝法師,FAIO,苔氏,kashi", "Open call DJ:Mangan,サル", "VJ:えいやん,みおに", "organizer:もなかさなか"],
        color: "#4ECDC4",
        url:"https://x.com/mimi0heart/status/2012774449011949640",
        image: "/images/vocalife.png",
    },
    { 
        id: 52, 
        title: "CHOCOL人´∀｀ATE!!!",
        type: "music", 
        year: "2026", 
        role: "Composition / Movie", 
        desc: "楽観的に生きるという楽曲を投稿しました", 
        detailText: "大きなトラブルが起きないよう、楽観的に、適当に過ごすことへの危機感をイメージして制作した楽曲です。\n\nAfter Effectのモーショングラフィックス、またトラッキングを軸にMVを制作しています。",
        credits: ["Composition,Movie:三面相", "STEM Mastering:Rei (studio JEN)"],
        color: "#FF6B6B",
        url:"https://www.nicovideo.jp/watch/sm45975101",
        image: "/images/CHOCOLATE.png",
    },
    { 
        id: 53, 
        title: "『Chill』コンピ ",
        type: "music", 
        year: "2026", 
        role: "Composition", 
        desc: "コンピレーションアルバムに参加しました", 
        detailText: "Lo-Fi Hip Hop,ボサノバ,シンセポップなどの『チルい音楽』が醸し出す音楽的要素と、様々な合成音声を掛け合わせた楽曲が集まる合成音声コンピレーションアルバムです。\n\n「あさのよかん」という楽曲で参加しています。",
        credits: ["Composition:三面相,あたたかい水族館,あなざ～せかい.,鮎川ぱて@しゅわしゅわP,稲むり,米教タルタル,桶屋-Okeya,オオウチアラタ,荻凪裕作,d.j.ァネイロ,ETE,ｋｏｎｄｏ,namitape,POPFACES,Rulmry.,uotak", "Mastering:SOZEN OTSUBO", "jacket design:のぞみ,おおつく(あなざ～せかい.)", "logo design:オオウチアラタ (Philtz),石川ひびき (Philtz)", "disc design:オオウチアラタ (Philtz)", "3D model:uotak(Philtz)", "Special Thanks,雨漏りP"],
        color: "#FF6B6B",
        url:"https://youtu.be/XBIYO-n2pRg",
        image: "/images/vocachillconpi.png",
    },
　  {   id: 54, 
        title: "三面相 - SANMENso Official Site",
        type: "fun", 
        year: "2026", 
        role: "Web design", 
        desc: "三面相のポートフォリオサイトを制作しました", 
        detailText: "自己紹介のできるウェブサイトを制作しました。\n\n三面相の活動を三つの面で表す、相互リンクをスクラッチのように見つける、隠しリンクを探せるなど、遊び心を盛り込んでいます。\n\n今後もコンテンツを追加していく予定です、ぜひ遊んでね。",
        credits: ["Web design:三面相"],
        color: "#FFD700",
        url:"",
        image: "/images/sanmensosite.png",
    },
    {   id: 55, 
        title: "足立って俺のダチ！？",
        type: "music", 
        year: "2026", 
        role: "Composition", 
        desc: "コンピレーションアルバムに参加しました", 
        detailText: "足立レイオンリーコンピレーションアルバム『足立って俺のダチ！？』に参加しました。\n\n機械的な要素を用いた、アップテンポな楽曲になっています。",
        credits: ["Composition:三面相,春川はしっこ,Aa,ナムササコ,砂糖の缶詰,空待澄人,にとろ,NNN,コットタウン,TENBIN,irukanotane,Mealerrand", "Jacket illust:夜風見", "Mastering:Saku"],
        color: "#FF6B6B",
        url:"https://youtu.be/Irqtj3njWSM",
        image: "/images/adatidati.png",
    },
    {   id: 56, 
        title: "『共創の測地線』アフターDJパーティ",
        type: "entame", 
        year: "2026", 
        role: "DJ", 
        desc: "イベントにDJで出演しました", 
        detailText: "”共創の測地線” アフターパーティにDJとして参加しました。",
        credits: ["DJ:三面相,風祭瑛紀,ぶき,cytokine,おた,Spam鍋"],
        url:"https://twipla.jp/events/720452",
        image: "/images/kyousoukansoku.png",
    },
    {   id: 57, 
        title: "ボカ脈in関西 Vol.2",
        type: "entame", 
        year: "2026", 
        role: "DJ", 
        desc: "イベントにDJで出演しました", 
        detailText: "『VOCALOID CONTEXT』ボカ脈in関西 Vol.2にDJとして参加しました。\n\n選曲に対する文脈を表現するという特殊なテーマのイベントでした。今回は【Vテレ】と題し、架空の教育テレビジョンを披露するようなパフォーマンスを行いました。",
        credits: ["DJ:三面相,あまのじゃく,毳蟲,とってい～,おおつく,chia*,RitA,ぴち", "VJ:めもる,梨音"],
        url:"https://twipla.jp/events/711380",
        image: "/images/vocamyaku.jpg",
    },
    {   id: 58, 
        title: "SMILEVIDEO in Osaka",
        type: "entame", 
        year: "2026", 
        role: "DJ", 
        desc: "イベントにDJで出演しました", 
        detailText: "ニコニコ動画を主としたイベントSMILEVIDEOにDJとして参加しました。\n",
        credits: ["DJ:シナガワ,mayo,CRすぴか.zip,temura,三面相,sentimental hardware,SH2MI2,YONEDA,sanmal,N4G1t,linterconnect", "VJ:sachia,R!QKN"],
        image: "/images/smile.png",
    },
];

export const EXCAVATION_LINKS = [
    { 
        id: 1,
        type: 'banner',
       url: "https://hozumi.site/",
        image: "https://hozumi.site/cdn/shop/t/6/assets/S__74637854.jpg?v=97761660025223919291763945063",
        alt: "あなたは青い部屋が好きですか？",
    },
    { 
        id: 2,
        type: 'banner',
        url: "https://ideoaves.github.io",
        image:"/images/banner/ideoaves_banner.png",
        alt: "ideoavesのホームページ",
    },
        { 
        id: 3,
        type: 'banner',
        url: "https://www.namigroove.com",
        image:"/images/banner/namigroove_banner01.png",
        alt: "なみぐるオフィシャルWEB バナー",
    },
    { 
        id: 4,
        type: 'banner',
        url: "http://tmpra.jp",
        image:"images/banner/tmpra_banner.png",
        alt: "TMPらのホームページ",
    },
    { 
        id: 5,
        type: 'banner',
        url: "https://sites.google.com/view/0-u2bo/home",
        image:"images/banner/U2bo_banner.png",
        alt: "Rei Utsuboのホームページ",
    },
    { 
        id: 6,
        type: 'banner',
        url: "https://www.awara-hasegawa.com/",
        image:"images/banner/hasegawa_banner.png",
        alt: "長谷川旅館のホームページ",
    },
    
];

export const SONGS = [
  {
    id: 1,
    title: "EPA EPA Txapeka",
    genre: "未来的Conplextro",
    duration: 180, 
    color: "#00FFDD", 
    bgAccent: "bg-[#00FFDD]",
    flavor: "NEON GLITCH POP",
    bpm: 128,
    src: "/audio/EPA EPA Txapeka.mp3" 
  },
  {
    id: 2,
    title: "Early Afternoon",
    genre: "冷凍Click House",
    duration: 210, 
    color: "#D8E2E5", 
    bgAccent: "bg-[#D8E2E5]",
    flavor: "CRYSTAL CUBE SODA",
    bpm: 110,
    src: "/audio/Early afternoon.mp3"
  },
   {
    id: 3,
    title: "Cut,solid,solar panel",
    genre: "CSS Core",
    duration: 195, 
    color: "#FF4500", 
    bgAccent: "bg-[#FF4500]",
    flavor: "CHAOS TROPICAL",
    bpm: 140,
    src: "/audio/Cut-solid-solar panel.mp3" 
  },
  {
    id: 4,
    title: "Im busy But Lonely",
    genre: "淡いelectro pop",
    duration: 195, 
    color: "#F48FB1", 
    bgAccent: "bg-[#F48FB1]",
    flavor: "LONELY PEACH PULP",
    bpm: 140,
    src: "/audio/Im busy But Lonely.mp3" 
  },
  {
    id: 5,
    title: "It started to Rein",
    genre: "不思議なアンビエントBGM",
    duration: 195, 
    color: "#076D6D", 
    bgAccent: "bg-[#076D6D]",
    flavor: "MYSTIC FOREST SAP",
    bpm: 140,
    src: "/audio/It started to Rein.mp3" 
  },
  {
    id: 6,
    title: "PouNtan tan",
    genre: "ハイテンションTech Core",
    duration: 195, 
    color: "#F3BB7A", 
    bgAccent: "bg-[#F3BB7A]",
    flavor: "HEAVY BLACK COLE",
    bpm: 140,
    src: "/audio/PouNtan tan.mp3" 
  },
  {
    id: 7,
    title: "splash rush",
    genre: "カットアップモリモリPop",
    duration: 195, 
    color: "#A4D65E", 
    bgAccent: "bg-[#A4D65E]",
    flavor: "FRESH SPLASH APPLE",
    bpm: 140,
    src: "/audio/splash rush.mp3" 
  }
]

export const SOCIAL_LINKS = [
    { name: 'X (Twitter)', url: 'https://x.com/SANMENSOUdrop' },
    { name: 'YouTube', url: 'https://www.youtube.com/@SANMENSOUdrop' },
    { name: 'niconico', url: 'https://www.nicovideo.jp/user/124526551' },
    { name: 'note', url: 'https://note.com/sanmen' },
    { name: 'booth', url: 'https://sanmen.booth.pm/' },
    { name: 'soundcloud', url: 'https://soundcloud.com/sanmenso' },
];

export const SITE_META = {
    title: '三面相 - SANMENso Official Site',
    description: '三面相のポートフォリオサイトです。楽曲制作、DJ、デザインなどの活動情報を掲載しています。',
    url: 'https://sanmenso.com', 
    siteName: 'SANMENso Official Site',
    locale: 'ja_JP',
    image: 'https://sanmenso.com/images/sanmenso_icon.jpg', // ※SNSで表示させたい画像のパス（1200x630px推奨）
    twitterCard: 'summary_large_image',
    twitterUsername: '@SANMENSOUdrop',
    type: 'website',
    favicon: '/favicon.ico',
};