export const THEME = {
    bgBase: '#f2f5f3',
    brandGreen: '#2E8B57',
    accentGold: '#FFD700',
    text: '#1a1a1a',
    black: '#121212',
    white: '#ffffff',
};

export const FONTS = {
    sans: '"Zen Kaku Gothic New", sans-serif',
    serif: '"Shippori Mincho", serif',
    mono: '"Courier New", Courier, monospace',
};

export const WORKS_DATA = [
    { 
        id: 1, 
        title: "ButterflyEffectCity/可不", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "活動者としての一歩目となる楽曲を作りました", 
        detailText: "ボカロPとしての一作目となる楽曲です。バタフライエフェクトというワードから連想し、一曲を仕上げました。",
        credits: ["Composition:三面相", "Illustration:らふぁえるsk"],
        color: "#FFD700" ,
        url: "https://youtu.be/TYKBm1GsSmA",
        image: "/images/butteerflyeffectCity.jpg",
    },
    { 
        id: 2, 
        title: "ナイト・アモーレ/星界", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "失恋した男に惚れている女性をテーマにした楽曲を作りました", 
        detailText: "星界楽曲コンテストへの参加曲として制作しました。昭和歌謡の雰囲気をゴリゴリに醸し出すという方向性で制作を進めました。",
        credits: ["Composition:三面相", "Illustration:櫛米"],
        color: "#FF6B6B" ,
        url: "https://youtu.be/yupa62YiQFg",
        image: "/images/nightamore.jpg",
    },
    { 
        id: 3, 
        title: "産声/可不・星界", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "民族的な要素を意識したデュエット曲を作りました", 
        detailText: "星界楽曲コンテストへの参加曲として制作しました。デュエットソングに挑戦してみようと思い、今までよりアコースティックな仕上がりを意識しました。",
        credits: ["Composition:三面相"],
        color: "#4ECDC4" ,
        url: "https://youtu.be/UOYN5jK454U",
        image: "/images/ubugoe.jpg",
    },
    { 
        id: 4, 
        title: "乱調ヒムノディ／星界", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "スランプ状態をテーマにした楽曲を作りました", 
        detailText: "スランプ状態に陥った時のメモをもとに制作した楽曲です。ボカコレに初参加しました。\n\nタイミング補正とピッチ補正で無理やりラップパートを作ったのは良い思い出です。",
        credits: ["Composition:三面相", "Movie:月華"],
        color: "#FFD700",
        url:"https://youtu.be/d4iwXL_yZNc",
        image: "/images/rantyou.jpg",
    },
    { 
        id: 5, 
        title: "電話線、三番ホーム/裏命", 
        type: "music", 
        year: "2022", 
        role: "Composition", 
        desc: "失恋をテーマにした楽曲を作りました", 
        detailText: "パンク的な楽曲。裏命楽曲コンテストに参加したときの曲です。\n\n頑張って地元を撮影していた痕跡があります。",
        credits: ["Composition:三面相", "VocalEdit:風祭瑛紀", "GuiterAssistant:花嶋"],
        color: "#4ECDC4",
        url:"https://youtu.be/-tQC2JsnOwc",
        image: "/images/denwasen3banhome.jpg",
    },
    { 
        id: 6, 
        title: "ボカロの資金がありません！！/初音ミク", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "「お金がない！」をテーマにした楽曲を作りました", 
        detailText: "お金がない！って曲です。当時のぼやきも入ってます。恥ずかしい。",
        credits: ["Composition:三面相", "Illustration:黒岩秀太!!"],
        color: "#4ECDC4",
        url:"https://www.nicovideo.jp/watch/sm41743994",
        image: "/images/novocaloidmoney.jpg",
    },
    { 
        id: 7, 
        title: "バベル/ノア", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "軽やかに歌い上げるケルト楽曲を作りました", 
        detailText: "バベルという楽曲です。ボカデュオというものに参加してみました。\n\n初めてボーカルを入れてもらった思い出深い楽曲でもあります。",
        credits: ["Composition:三面相", "Illustration,Movie:櫛米","Vocal:Fusb"],
        color: "#FF6B6B",
        url:"https://youtu.be/KSlT4hv3QKw",
        image: "/images/babel.jpg",
    },
    { 
        id: 8, 
        title: "レボルシオン/狐子", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "真っすぐなロック楽曲を作りました", 
        detailText: "真っすぐなロック楽曲。狐子楽曲コンテストに参加したときの曲です。",
        credits: ["Composition:三面相"],
        color: "#4ECDC4",
        url:"https://youtu.be/Nu3TOOYh6-4",
        image: "/images/reborusion.jpg",
    },
    { 
        id: 9, 
        title: "【DTM鯖】ダンスロボットダンス", 
        type: "music", 
        year: "2023", 
        role: "Remix", 
        desc: "リミックス合作に参加しました", 
        detailText: "DTM鯖合作に参加しました。ダンスロボットダンスのリミックスです。",
        credits: ["Remixer:	Aa, cottown, lyqjw, mikage, nahi, Taguchi Hideo, だいす, レラー, 荒井　暁, 三面相, 澄石亜卵, 長谷川迷子, 夢見川るい, 鼬炉ヒソ", "Illustration: 桶猫, 残響室, 森永謹製, 米村ソウマ"],
        color: "#4ECDC4",
        url:"https://www.nicovideo.jp/watch/sm42576695",
        image: "/images/dancerobotRemix.jpg",
    },
    { 
        id: 10, 
        title: "エンドロールの箱で/花奏かのんβ", 
        type: "music", 
        year: "2023", 
        role: "Composition", 
        desc: "一年の終わりをイメージした曲を作りました", 
        detailText: "年の瀬に楽曲を制作しました。渋谷系とハイパーフリップを自分なりに落とし込もうと考えた結果、情報量をカットアップによって埋め尽くすことを考えてました。",
        credits: ["Composition:三面相"],
        color: "#4ECDC4",
        url:"https://youtu.be/n_s7wbispd4",
        image: "/images/endrolebox.jpg",
    },
    { 
        id: 11, 
        title: "きっと : だれか ; ぼくら / 可不", 
        type: "music", 
        year: "2024", 
        role: "Composition", 
        desc: "旅立つ人へのエールを送る曲を作りました", 
        detailText: "独り立ちする自分をテーマに制作した楽曲です。渋谷系の音楽を自分なりに落とし込み、カットアップを多様したポップスを制作しました。\n\n撮影のロケーションは全て地元です。コマ撮りを力業で行いました。",
        credits: ["Composition:三面相", "Movie:三面相"],
        color: "#4ECDC4",
        url:"https://youtu.be/egZJaL9Lq3I",
        image: "/images/kittodarekabokura.jpg",
    },
    { 
        id: 12, 
        title: "ょく / 初音ミク【三択はむり】", 
        type: "music", 
        year: "2024", 
        role: "Arrangement", 
        desc: "『ょく』という楽曲に編曲で参加しました", 
        detailText: "ボカタッグというイベントにて三択はむりというチームを組みました。編曲を担当しました。\n\n荘厳な雰囲気から始まり、フューチャーベースのようなドロップに繋がる展開は、作っていてとても楽しかったです。",
        credits: ["Composition:稲むり", "Arrangement:三面相", "Illustration:uotak", "Movie:木葉はづく"],
        color: "#4ECDC4",
        url:"https://www.nicovideo.jp/watch/sm43683720",
        image: "/images/yoku.jpg",
    },
    { 
        id: 13, 
        title: "【猫じゃらし道】それと同じ陽の暖かさ / ゲキヤクβ・カゼヒキβ", 
        type: "music", 
        year: "2024", 
        role: "Arrangement", 
        desc: "『ょく』という楽曲に編曲で参加しました", 
        detailText: "ボカタッグというイベントにて猫じゃらし道というチームを組みました。編曲を担当しました。\n\n「テクノポップにしてください」というオーダーを受け、楽曲のやさしさの部分とテクノポップを両立させられるように意識して制作しました。",
        credits: ["Composition:稲むり", "Arrangement:三面相", "Illustration:並木道", "Movie:稲むり"],
        color: "#4ECDC4",
        url:"https://youtu.be/15z0vwS77u0",
        image: "/images/soretoonaji.jpg",
    },
    { 
        id: 14, 
        title: "『鏡像異性体』出演", 
        type: "entame", 
        year: "2024", 
        role: "DJ", 
        desc: "鏡像異性体というイベントにDJで出演しました", 
        detailText: "合成音声系のDJイベントに出演しました。第一回のイベントで初めてのDJ出演という、貴重な機会を頂きました。",
        credits: ["DJ:三面相,芥田レンリ,Right,ざき,Uyamichi,Uyamichi", "VJ:扉,Zect", "Staff:アライグマ,観測者48", "Organizer:風祭瑛紀"],
        color: "#4ECDC4",
        url:"https://x.com/enantiomer_eve/status/1790714101284676068",
        image: "/images/kyoudouiseitaiVol1.jpg",
    },
    { 
        id: 15, 
        title: "V.A. - SUPER MURAKAMI BEST HITS", 
        type: "music", 
        year: "2024", 
        role: "Composition", 
        desc: "声ネタ縛りコンピレーションアルバムに参加しました", 
        detailText: "村上苺さんのボイスサンプルを用いた楽曲を作るというコンピレーションアルバムに楽曲を提供しました。声ネタはなんぼあってもいい。",
        credits: ["Composition:ijimi,trekk,ハヤトムラカミ,10-U,crash909☆ 啊痾誒都哇嗚哇咦,糸魚川 鼎,M9RVEN,Legend of 阪口,Eyhz & Violet Delta,dj patriot,Kaichirock,Ide_Co,LieDeeDonk,ドンツカチェィッフォー,WⱯꓥƎ,ゴローニャ雨宮,三面相","Special Thanks:村上苺","Illustration:HUKRiTAX","Design:Occupied Territories","Organizer:Lost Frog Productions"],
        color: "#4ECDC4",
        url:"https://lostfrog.bandcamp.com/album/super-murakami-best-hits",
        image: "/images/murakamibest.jpg",
    },
];

export const EXCAVATION_LINKS = [
    { 
        id: 1,
        type: 'banner',
        url: "https://hozumi.site/",
        image: "https://hozumi.site/cdn/shop/t/6/assets/S__74637854.jpg?v=97761660025223919291763945063",
        alt: "あなたは青い部屋が好きですか？",
    },
    { 
        id: 2,
        type: 'banner',
        url: "https://ideoaves.github.io",
        image:"https://ideoaves.github.io/banner.png",
        alt: "ideoavesのホームページ",
    },
        { 
        id: 3,
        type: 'banner',
        url: "https://www.namigroove.com",
        image:"https://www.namigroove.com/wp-content/uploads/2023/12/namigroove_banner01.png",
        alt: "なみぐるオフィシャルWEB バナー",
    },
  { 
        id: 4,
        type: 'banner',
        url: "http://tmpra.jp",
        image:"http://tmpra.jp/Banner.png",
        alt: "TMPらのホームページ",
    },
    
];

export const SONGS = [
  {
    id: 1,
    title: "EPA EPA Txapeka",
    genre: "未来的Conplextro",
    duration: 180, 
    color: "#00FFDD", 
    bgAccent: "bg-[#00FFDD]",
    flavor: "NEON GLITCH POP",
    bpm: 128,
    src: "/audio/EPA EPA Txapeka.wav" 
  },
  {
    id: 2,
    title: "Early Afternoon",
    genre: "冷凍Click House",
    duration: 210, 
    color: "#D8E2E5", 
    bgAccent: "bg-[#D8E2E5]",
    flavor: "CRYSTAL CUBE SODA",
    bpm: 110,
    src: "/audio/Early afternoon.mp3"
  },
   {
    id: 3,
    title: "Cut,solid,solar panel",
    genre: "CSS Core",
    duration: 195, 
    color: "#FF4500", 
    bgAccent: "bg-[#FF4500]",
    flavor: "CHAOS TROPICAL",
    bpm: 140,
    src: "/audio/Cut-solid-solar panel.wav" 
  },
  {
    id: 4,
    title: "Im busy But Lonely",
    genre: "淡いelectro pop",
    duration: 195, 
    color: "#F48FB1", 
    bgAccent: "bg-[#F48FB1]",
    flavor: "LONELY PEACH PULP",
    bpm: 140,
    src: "/audio/Im busy But Lonely.wav" 
  },
  {
    id: 5,
    title: "It started to Rein",
    genre: "不思議なアンビエントBGM",
    duration: 195, 
    color: "#076D6D", 
    bgAccent: "bg-[#076D6D]",
    flavor: "MYSTIC FOREST SAP",
    bpm: 140,
    src: "/audio/It started to Rein.mp3" 
  },
  {
    id: 6,
    title: "PouNtan tan",
    genre: "ハイテンションTech Core",
    duration: 195, 
    color: "#F3BB7A", 
    bgAccent: "bg-[#F3BB7A]",
    flavor: "HEAVY BLACK COLE",
    bpm: 140,
    src: "/audio/PouNtan tan.mp3" 
  },
  {
    id: 7,
    title: "splash rush",
    genre: "カットアップモリモリPop",
    duration: 195, 
    color: "#A4D65E", 
    bgAccent: "bg-[#A4D65E]",
    flavor: "FRESH SPLASH APPLE",
    bpm: 140,
    src: "/audio/splash rush.wav" 
  }
]

export const SOCIAL_LINKS = [
    { name: 'X (Twitter)', url: 'https://x.com/SANMENSOUdrop' },
    { name: 'YouTube', url: 'https://www.youtube.com/@SANMENSOUdrop' },
    { name: 'niconico', url: 'https://www.nicovideo.jp/user/124526551' },
    { name: 'note', url: 'https://note.com/sanmen' },
    { name: 'booth', url: 'https://sanmen.booth.pm/' },
    { name: 'soundcloud', url: 'https://soundcloud.com/sanmenso' },
];